[package]
name = "runvoid"
version = "0.2.0"
edition = "2024"
authors = ["runvoid"]
description = "A simple, ultra-fast scripting-feel compiled language written in Rust and NASM"
license = "GPL-3.0-or-later"
repository = "https://github.com/runvoid/runvoid"
readme = "README.md"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
